// Fig.4 generator: e2_snr.csv -> fig4_snr.tex (pure pgfplots, no extra
// libraries; +-1 std bands emitted as raw \fill polygons).
// Usage: node fig4_snr.mjs <e2_snr.csv> <outdir> [conds=c1,c2,c3] [ymax=4.5]
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";

const [csvPath, outDir, condsArg, ymaxArg] = process.argv.slice(2);
const ymax = parseFloat(ymaxArg || "4.5");
const want = condsArg ? condsArg.split(",") : null;
mkdirSync(outDir, { recursive: true });

// parse summary csv: condition,algorithm,snr_db,n,mean,std,median,success
const lines = readFileSync(csvPath, "utf8").trim().split(/\r?\n/).slice(1);
const data = {}; // cond -> algo -> [{snr, mean, std, med, ok}]
for (const ln of lines) {
  const [cond, algo, snr, n, mean, std, med, ok] = ln.split(",");
  (data[cond] ??= {})[algo] ??= [];
  if (snr === "clean") continue;
  data[cond][algo].push({ snr: +snr, mean: +mean, std: +std, med: +med, ok: +ok });
}
const conds = Object.keys(data).filter(c => !want || want.includes(c));

const ALGOS = [
  ["CBF", "cbf", { draw: "black", mark: "*", fill: "white" }],
  ["MVDR", "mvdr", { draw: "black", mark: "*", fill: "black" }],
  ["MUSIC", "music", { draw: "black", mark: "triangle", fill: "gray!25" }],
  ["MUSIC_CSDM", "music_csdm", { draw: "black", mark: "square", fill: "gray!60" }],
];
const BANDFILL = { CBF: "black!12", MVDR: "black!12", MUSIC: "black!8", MUSIC_CSDM: "black!8" };

const condTitle = c => {
  const [f, d] = c.split("Hz_");
  return `${(f / 1000).toFixed(0)}~kHz / ${d}~m`;
};

let tex = `%% fig4_snr.tex -- generated by fig4_snr.mjs; paste axis envs into main.tex
%% requires only \\usepackage{pgfplots} + \\usetikzlibrary{arrows.meta}
\\begin{figure}[!t]
\\centering
\\begin{tikzpicture}[font=\\tiny]
`;
conds.forEach((cond, ci) => {
  const last = ci === conds.length - 1;
  const at = ci === 0 ? "0,0" : "a" + (ci - 1) + ".south";
  const anchor = ci === 0 ? "north west" : "north, yshift=-18pt";
  tex += `\\begin{axis}[name=a${ci}, at={(${at})}, anchor=${anchor},
`;
  tex += `  width=\\linewidth-16pt, height=3.1cm,
  xmin=-21, xmax=21, ymin=0, ymax=${ymax},
${last ? "  xlabel={Injected SNR (dB)}, " : "  "}ylabel={Error (m)},
  xtick={-20,-10,0,10,20}, ytick={0,1,2,3,4},
  title={\\bfseries ${condTitle(cond)}}, title style={at={(rel axis cs:0.03,0.96)}, anchor=north west, yshift=-2pt},${ci === 0 ? `
  legend columns=4, legend style={at={(0.5,1.05)}, anchor=south, draw=none, fill=none, /tikz/every even column/.append style={column sep=8pt}}, legend entries={CBF,MVDR,MUSIC,CSDM-MUSIC},` : ""}
  ymajorgrids]
`;
  // +-1 std band polygons (upper fwd, lower rev)
  for (const [A] of ALGOS) {
    const pts = data[cond][A];
    if (!pts?.length) continue;
    const up = pts.map(p => `(axis cs:${p.snr},${Math.min(ymax, p.mean + p.std).toFixed(3)})`).join(" -- ");
    const lo = [...pts].reverse().map(p => `(axis cs:${p.snr},${Math.max(0, p.mean - p.std).toFixed(3)})`).join(" -- ");
    tex += `\\path[fill=${BANDFILL[A]}] ${up} -- ${lo} -- cycle;\n`;
  }
  // curves
  for (const [A, , st] of ALGOS) {
    const pts = data[cond][A];
    if (!pts?.length) continue;
    const coords = pts.map(p => `(${p.snr},${p.mean.toFixed(3)})`).join(" ");
    tex += `\\addplot[draw=${st.draw}, mark=${st.mark}, mark size=1.6pt, mark options={fill=${st.fill},draw=black}, line width=0.5pt] coordinates {${coords}};\n`;
  }
  tex += `\\draw[dashed] (axis cs:-21,0.5) -- (axis cs:21,0.5);\n\\end{axis}\n`;
});
tex += `\\end{tikzpicture}
\\caption{Mean localization error (over 20 projector events, $\\pm$1 std shaded)
versus injected band-matched noise SNR for the four algorithms in three
projector conditions (post-processing injection on the original 8-channel
recordings; dashed: 0.5~m failure threshold).}
\\label{fig:snr}
\\end{figure}
`;
writeFileSync(join(outDir, "fig4_snr.tex"), tex);

// standalone preview wrapper
const standalone = `\\documentclass[border=2pt]{standalone}
\\usepackage{pgfplots}
\\pgfplotsset{compat=1.17}
\\usetikzlibrary{arrows.meta}
\\begin{document}
${tex.replace(/\\begin\{figure\}(\[!t\])?/, "").replace(/\\end\{figure\}/, "").replace(/\\caption\{[\s\S]*$/m, "")}
\\end{document}
`;
writeFileSync(join(outDir, "fig4_snr_standalone.tex"), standalone);
console.log(`wrote fig4_snr.tex (${conds.length} panels: ${conds.join(", ")})`);
